# Generated by Django 5.1.5 on 2025-01-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_products_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
